import { VocabEntry } from '../types';

interface ArchiveSet {
  tableId: string;
  title: string;
  loader: () => Promise<{ entries: VocabEntry[] }>;
}

// Maps each unlocked collection ID to the individual sets it contains.
// This matches the table IDs generated by SystemArchives.tsx.
const archiveSetMap: Record<string, ArchiveSet[]> = {
  'ielts-a1': [
    { tableId: 'system-ielts-a1', title: 'IELTS A1 Vocabulary', loader: () => import('../src/data/ielts_a1.json').then(m => m.default || m) },
  ],
  'ielts-a2': [
    { tableId: 'system-ielts-a2', title: 'IELTS A2 Vocabulary', loader: () => import('../src/data/ielts_a2.json').then(m => m.default || m) },
  ],
  'ielts-b1': [
    { tableId: 'system-ielts-b1', title: 'IELTS B1 Vocabulary', loader: () => import('../src/data/ielts_b1.json').then(m => m.default || m) },
  ],
  'ielts-b2': [
    { tableId: 'system-ielts-b2', title: 'IELTS B2 Vocabulary', loader: () => import('../src/data/ielts_b2.json').then(m => m.default || m) },
  ],
  'ielts-c1': [
    { tableId: 'system-ielts-c1', title: 'IELTS C1 Vocabulary', loader: () => import('../src/data/ielts_c1.json').then(m => m.default || m) },
  ],
  'ielts-c2': [
    { tableId: 'system-ielts-c2', title: 'IELTS C2 Vocabulary', loader: () => import('../src/data/ielts_c2.json').then(m => m.default || m) },
  ],
  'sat-college-panda-400': [
    { tableId: 'system-sat-college-panda-400-set-1', title: 'College Panda 400 - Set 1', loader: () => import('../src/data/sat_college_panda1.json').then(m => m.default || m) },
    { tableId: 'system-sat-college-panda-400-set-2', title: 'College Panda 400 - Set 2', loader: () => import('../src/data/sat_college_panda2.json').then(m => m.default || m) },
    { tableId: 'system-sat-college-panda-400-set-3', title: 'College Panda 400 - Set 3', loader: () => import('../src/data/sat_college_panda3.json').then(m => m.default || m) },
    { tableId: 'system-sat-college-panda-400-set-4', title: 'College Panda 400 - Set 4', loader: () => import('../src/data/sat_college_panda4.json').then(m => m.default || m) },
  ],
  'sat-erica-vocabulary': [
    { tableId: 'system-sat-erica-vocabulary-academic-vocabulary', title: 'Erica Vocabulary - Set 1', loader: () => import('../src/data/sat_erica1.json').then(m => m.default || m) },
    { tableId: 'system-sat-erica-vocabulary-additional-general', title: 'Erica Vocabulary - Set 2', loader: () => import('../src/data/sat_erica2.json').then(m => m.default || m) },
    { tableId: 'system-sat-erica-vocabulary-common-second-meanings', title: 'Erica Vocabulary - Set 3', loader: () => import('../src/data/sat_erica3.json').then(m => m.default || m) },
    { tableId: 'system-sat-erica-vocabulary-look-negative-but-arent', title: 'Erica Vocabulary - Set 4', loader: () => import('../src/data/sat_erica4.json').then(m => m.default || m) },
    { tableId: 'system-sat-erica-vocabulary-set-5', title: 'Erica Vocabulary - Set 5', loader: () => import('../src/data/sat_erica5.json').then(m => m.default || m) },
  ],
};

const cache = new Map<string, VocabEntry[]>();

export const loadUnlockedArchiveEntries = async (
  unlockedIds: string[]
): Promise<{ tableId: string; title: string; entries: VocabEntry[] }[]> => {
  const results: { tableId: string; title: string; entries: VocabEntry[] }[] = [];

  for (const id of unlockedIds) {
    const sets = archiveSetMap[id];
    if (!sets) continue;

    for (const set of sets) {
      let entries = cache.get(set.tableId);
      if (!entries) {
        try {
          const data = await set.loader();
          entries = data.entries || [];
          cache.set(set.tableId, entries);
        } catch (e) {
          console.error(`Failed to load archive set ${set.tableId}:`, e);
          continue;
        }
      }

      results.push({ tableId: set.tableId, title: set.title, entries });
    }
  }

  return results;
};

export const clearArchiveCache = () => cache.clear();

// All valid individual system table IDs, used to filter out stale combined tables.
export const validSystemTableIds: Set<string> = new Set(
  Object.values(archiveSetMap).flatMap(sets => sets.map(s => s.tableId))
);
